Milestone 3-Final  touches
eudondian/Leaderboard pull request #3
Opened 2022-07-29 21:39 UTC by eudondian

Added styles to the Application

2022-07-29 21:57 UTC, Deepakdanger requested changes
Hi @eudondian, 

Good job so far! 👏
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight :100: 
- No linter error :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-29 21:57 UTC, Deepakdanger commented on src/modules/service.js
> +
- [ ] When trying to submit the score, I can't able to submit it to leaderboard API. Please fix it.

2022-07-29 21:57 UTC, Deepakdanger commented on src/styles/style.css
> +}
- [ ] Also, keep your design similar to the wireframe. The input form should be on the right.


### Your design
![Screenshot from 2022-07-30 03-26-00](https://user-images.githubusercontent.com/26767383/181848125-9c1d1b63-7c32-42f1-b93e-4e96825076ab.png)

### Given design
![Screenshot from 2022-07-30 03-24-45](https://user-images.githubusercontent.com/26767383/181848136-4d35e933-0de3-4c5d-b1fc-addc9221d03b.png)

2022-07-30 11:13 UTC, Ghiftee approved these changes
## STATUS: APPROVED ♻️♻️
Hi @eudondian, 

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀  
Congratulations! 🎉 

![](https://media.giphy.com/media/xT0xezQGU5xCDJuCPe/giphy.gif)

Cheers and Happy coding!👏👏👏

2022-07-30 19:57 UTC, merged